# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('Crt_Time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('Upd_Time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account_id', models.AutoField(primary_key=True, serialize=False, verbose_name='表ID')),
                ('account_name', models.CharField(max_length=60, verbose_name='表名')),
                ('account_photo', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='', verbose_name='默认图片')),
            ],
            options={
                'verbose_name': '账号表',
                'verbose_name_plural': '账号表',
                'db_table': 'TAB_Account',
            },
        ),
    ]
