# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-19 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinfo',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='用户ID'),
        ),
    ]
