# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-19 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expenseinfo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinfo',
            name='expense_content',
            field=models.CharField(default='', max_length=100, verbose_name='消费备注'),
        ),
    ]
