# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillInfo',
            fields=[
                ('Crt_Time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('Upd_Time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bill_id', models.AutoField(primary_key=True, serialize=False, verbose_name='表ID')),
                ('account_id', models.IntegerField(verbose_name='账号ID')),
                ('bill_name', models.CharField(max_length=60, verbose_name='表名')),
                ('bill_auth', models.CharField(max_length=5, verbose_name='权限')),
                ('bill_members', models.CharField(max_length=60, verbose_name='成员')),
            ],
            options={
                'verbose_name': '账单表',
                'verbose_name_plural': '账单表',
                'db_table': 'TAB_BILL',
            },
        ),
    ]
