# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-19 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinfo',
            old_name='account_id',
            new_name='user_id',
        ),
    ]
