# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-19 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20200719_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinfo',
            name='bill_members',
            field=models.CharField(default='', max_length=60, verbose_name='成员'),
        ),
    ]
