# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-12-31 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_spiders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestseller',
            name='brand',
            field=models.CharField(default='', max_length=30, verbose_name='品牌或者店铺'),
        ),
    ]
