# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-12-31 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_spiders', '0002_bestseller_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestseller',
            name='goods_url',
            field=models.CharField(max_length=300, verbose_name='访问页面url'),
        ),
    ]
