# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-12-31 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_spiders', '0003_auto_20201231_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestseller',
            name='img_url',
            field=models.CharField(max_length=300, verbose_name='照片url'),
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
    ]
