# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-12-31 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_spiders', '0004_auto_20201231_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestseller',
            name='s_time',
            field=models.CharField(max_length=30, verbose_name='爬取日期'),
        ),
    ]
