# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-12-31 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_spiders', '0005_auto_20201231_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestseller',
            name='name',
            field=models.CharField(max_length=300, verbose_name='名称'),
        ),
    ]
