# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-12-31 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_spiders', '0006_auto_20201231_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestseller',
            name='category',
            field=models.CharField(default='', max_length=50, verbose_name='类目名'),
        ),
    ]
