# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-01-04 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_spiders', '0007_bestseller_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestseller',
            name='price',
            field=models.CharField(max_length=100, verbose_name='价格'),
        ),
    ]
